# Generated by Django 5.2.9 on 2026-03-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('series_name', models.CharField(max_length=100)),
                ('class_field', models.CharField(db_column='class', max_length=20)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('purchase_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purchase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_upto', models.DateField(blank=True, null=True)),
                ('sent_to_school', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'purchase_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_name', models.CharField(max_length=150)),
                ('school_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('password_hash', models.CharField(max_length=200)),
                ('branch', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'school',
                'managed': False,
            },
        ),
    ]
