# Generated by Django 5.0.4 on 2026-02-18 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('series_name', models.CharField(max_length=100)),
                ('class_num', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=50, unique=True)),
                ('school_id', models.CharField(max_length=50)),
                ('password_hash', models.CharField(max_length=255)),
                ('teacher_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('school_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samsel_website.books')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samsel_website.teacher')),
            ],
        ),
    ]
