# Generated by Django 5.2.10 on 2026-02-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('series_name', models.CharField(max_length=150)),
                ('class_name', models.CharField(db_column='class', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_id', models.CharField(max_length=50)),
                ('t_id', models.CharField(max_length=50)),
                ('book_id', models.CharField(max_length=50)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('valid_upto', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=50)),
                ('school_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('t_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=50)),
                ('school_id', models.CharField(max_length=50)),
                ('school_name', models.CharField(blank=True, max_length=150, null=True)),
                ('password_hash', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('no_of_series_purchased', models.IntegerField(default=0)),
                ('purchase_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
