# Generated by Django 5.0.4 on 2026-02-19 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samsel_website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='password_hash',
            new_name='password',
        ),
    ]
