# Generated by Django 5.2.9 on 2026-03-12 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samsel_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={},
        ),
        migrations.AlterModelOptions(
            name='purchaseitems',
            options={},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={},
        ),
    ]
