# Generated by Django 5.2.9 on 2026-03-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samsel_website', '0002_rename_password_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_upto', models.DateField(blank=True, null=True)),
                ('sent_to_school', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'purchase_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_name', models.CharField(max_length=150)),
                ('school_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('password_hash', models.CharField(max_length=200)),
                ('branch', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'school',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'managed': False},
        ),
    ]
